"""Content generation, coverage validation, and stats helpers.

Extracted from ``distributed_compiler`` to keep that module ≤500 lines.
All functions receive collaborators (link_resolver, context_optimizer) as
explicit parameters rather than accessing compiler instance state, making
them independently testable.
"""

import builtins
from pathlib import Path

from ..primitives.models import Instruction, PrimitiveCollection
from ..utils.paths import portable_relpath
from ..version import get_version
from ._dc_models import PlacementResult
from .constants import BUILD_ID_PLACEHOLDER
from .template_builder import render_instructions_block


def generate_agents_content(
    placement: PlacementResult,
    primitives: PrimitiveCollection,
    link_resolver: object,
    base_dir: Path,
) -> str:
    """Generate AGENTS.md content for a specific placement.

    Args:
        placement: Placement result with instructions.
        primitives: Full primitive collection (reserved for future use).
        link_resolver: UnifiedLinkResolver instance.
        base_dir: Project root directory.

    Returns:
        Generated AGENTS.md content.
    """
    sections = []

    # Header with source attribution
    sections.append("# AGENTS.md")
    sections.append("<!-- Generated by APM CLI from distributed .apm/ primitives -->")
    sections.append(BUILD_ID_PLACEHOLDER)
    sections.append(f"<!-- APM Version: {get_version()} -->")

    # Add source attribution summary if enabled
    if placement.source_attribution:
        sources = set(placement.source_attribution.values())
        if len(sources) > 1:
            sections.append(f"<!-- Sources: {', '.join(sorted(sources))} -->")
        else:
            sections.append(f"<!-- Source: {next(iter(sources), 'local')} -->")

    sections.append("")

    def _emit(instruction: Instruction) -> builtins.list[str]:
        lines: builtins.list[str] = []
        if placement.source_attribution:
            source = placement.source_attribution.get(str(instruction.file_path), "local")
            rel_path = portable_relpath(instruction.file_path, base_dir)
            lines.append(f"<!-- Source: {source} {rel_path} -->")
        lines.append(instruction.content.strip())
        lines.append("")
        return lines

    sections.extend(
        render_instructions_block(
            placement.instructions,
            base_dir=base_dir,
            emit_instruction=_emit,
        )
    )

    # Footer
    sections.append("---")
    sections.append("*This file was generated by APM CLI. Do not edit manually.*")
    sections.append("*To regenerate: `apm compile`*")
    sections.append("")

    content = "\n".join(sections)

    # Resolve context links in the generated content
    content = link_resolver.resolve_links_for_compilation(
        content=content,
        source_file=placement.agents_path.parent,
        compiled_output=placement.agents_path,
    )

    return content


def validate_coverage(
    placements: builtins.list[PlacementResult],
    all_instructions: builtins.list[Instruction],
) -> builtins.list[str]:
    """Validate that all instructions are covered by placements.

    Args:
        placements: Generated placements.
        all_instructions: All available instructions.

    Returns:
        List of coverage warnings.
    """
    warnings = []
    placed_instructions = set()

    for placement in placements:
        placed_instructions.update(str(inst.file_path) for inst in placement.instructions)

    all_instruction_paths = set(str(inst.file_path) for inst in all_instructions)

    missing_instructions = all_instruction_paths - placed_instructions
    if missing_instructions:
        warnings.append(
            f"Instructions not placed in any AGENTS.md: {', '.join(missing_instructions)}"
        )

    return warnings


def compile_distributed_stats(
    placements: builtins.list[PlacementResult],
    primitives: PrimitiveCollection,
    context_optimizer: object,
) -> builtins.dict[str, float]:
    """Compile statistics about the distributed compilation with optimization metrics.

    Args:
        placements: Generated placements.
        primitives: Full primitive collection.
        context_optimizer: ContextOptimizer instance.

    Returns:
        Compilation statistics including optimization metrics.
    """
    total_instructions = sum(len(p.instructions) for p in placements)
    total_patterns = sum(len(p.coverage_patterns) for p in placements)

    # Get optimization metrics
    placement_map = {Path(p.agents_path.parent): p.instructions for p in placements}
    optimization_stats = context_optimizer.get_optimization_stats(placement_map)

    # Combine traditional stats with optimization metrics
    stats: builtins.dict[str, float] = {
        "agents_files_generated": len(placements),
        "total_instructions_placed": total_instructions,
        "total_patterns_covered": total_patterns,
        "primitives_found": primitives.count(),
        "chatmodes": len(primitives.chatmodes),
        "instructions": len(primitives.instructions),
        "contexts": len(primitives.contexts),
    }

    # Add optimization metrics from OptimizationStats object
    if optimization_stats:
        stats.update(
            {
                "average_context_efficiency": optimization_stats.average_context_efficiency,
                "pollution_improvement": optimization_stats.pollution_improvement,
                "baseline_efficiency": optimization_stats.baseline_efficiency,
                "placement_accuracy": optimization_stats.placement_accuracy,
                "generation_time_ms": optimization_stats.generation_time_ms,
                "total_agents_files": optimization_stats.total_agents_files,
                "directories_analyzed": optimization_stats.directories_analyzed,
            }
        )

    return stats
